### ISSUE TITLE
how can i train it on remote system.

### ISSUE THREAD

**Issue by zituka** [NVIDIA-Omniverse/IsaacGymEnvs#13]
Hi, thx for the great job on  IsaacGymEnvs!
I don’t own a local desktop machine, I rely on remote cluster for GPUs. I have headless docker + ssh./ conda + ssh. ,(i tried VNC, but it seems not good on isaac gym)
All the python/examples show segfault, RL env report the same segfault core dump error. I looked up a lot of methods but nothing worked. How can i train it just on terminal?

**Comment by HaozhiQi** [comment]
Have you tried to set `headless: True` in `cfg/config.yaml`?

**Comment by zituka** [comment]
> 

many thanks for your reply, i forgot that.. it looks good now!

**Comment by abayomi185** [comment]
Hi, is it possible to view the graphics environment on the remote system using VNC, RDP or perhaps from Docker?
