### ISSUE TITLE
A quickstart guide for RL researchers

### ISSUE THREAD

**Issue by metekemertas** [NVIDIA-Omniverse/IsaacGymEnvs#15]
Is there an easy way to use IsaacGym environments to test research code? I've been struggling to do the equivalent of this with IsaacGym for hours now despite sifting through tons of documentation. A quick-start guide like below would greatly help researchers who may not necessarily want to commit to `rl_games` or use the `train.py` script, but quickly integrate their own code & torch models for benchmarking with little-to-no overhead.

<img width="888" alt="Screen Shot 2022-01-27 at 12 38 42 AM" src="https://user-images.githubusercontent.com/6467420/151259480-6b987422-caa3-4bbd-8935-9a25855e0a70.png">

**Comment by gavrielstate** [comment]
If you don't want to use the training scripts in the IsaacGymEnvs repository, but just want to use Isaac Gym as a simulator with other RL frameworks, you may want to look instead at the example scripts in the python/examples directory in the main IsaacGym download. These should provide much simpler examples of how to set up and run basic simulations.
