### ISSUE TITLE
Documentation should be updated

### ISSUE THREAD

**Issue by noshaba** [NVIDIA-Omniverse/IsaacGymEnvs#17]
Hi,

The documentation, e.g. in https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/main/docs/framework.md should probably be updated.

**Comment by gavrielstate** [comment]
Can you be more specific about what you think needs to be updated?

**Comment by noshaba** [comment]
For example it states that the __init__ method only takes 3 arguments - the config file, sim_device and headless. Yet, in the examples, they also include graphics_device_id. Also the parameters required for the config files and what they mean and which options you have for them would be nice to have written somewhere in a more formal and organized way.

**Comment by noshaba** [comment]
So at least a minimum hello world example, similar to the Hello World / Robot examples in Isaac Sim.

**Comment by noshaba** [comment]
Another improvement for the docs could be to add that jit functions should all have unique names. It doesn't work if the same function name for the reward and observation function are used in different tasks but the error messages you get don't indicate that. Only says that the task X could not be imported.
