### ISSUE TITLE
How long does it take to train the IndustReal Insertion task

### ISSUE THREAD

**Issue by changhaonan** [NVIDIA-Omniverse/IsaacGymEnvs#188]
Hi,

I want to ask how long does it take to train the IndustReal Insertion task on a single 3090 card. My current testing is that it takes around 10 hours to train 1024 epochs. The default epochs is 8192, so it takes around 80 hours? My fps step is around 600. Is there anything I did wrong?

Best,
Haonan Chang

**Comment by bingjietang718** [comment]
Hi Haonan, 

Thank you for your interest in IndustReal! Normally I will stop the policy training when I see the logged success rate reaches ~85% at the most difficult level of curriculum (i.e. logged `curr_max_disp=-0.01`). You can check the logged success rate and current curriculum difficulty level on [WandB](https://wandb.ai/) after setting up your own account and run the training code with `wandb_activate=True`.

Best,
Bingjie
