### ISSUE TITLE
KeyError when loading usd in franka_cube_ik_osc.py example 

### ISSUE THREAD

**Issue by janisa9** [NVIDIA-Omniverse/IsaacGymEnvs#19]
The documentation says the following: 

`The load_asset method uses the file name extension to determine the asset file format. Supported extensions include .urdf for URDF files, .xml for MJCF files, and .usd/.usda for USD files. `

However when I change the asset in franka_cube_ik_osc.py example to "urdf/franka_description/robots/franka_panda/franka_panda.usd" I get the following error: 

`Traceback (most recent call last):
  File "franka_cube_ik_osc.py", line 208, in <module>
    franka_hand_index = franka_link_dict["panda_hand"]
KeyError: 'panda_hand'`

Is there something in the example code that is not compatible with usd format?

**Comment by gavrielstate** [comment]
Sorry - this is a documentation error. The standalone Isaac Gym Preview release does not support loading USD I'm afraid. That will of course change with Omniverse Isaac Gym.
