### ISSUE TITLE
why my urdf can't work in isaac gym?

### ISSUE THREAD

**Issue by shitoujie** [NVIDIA-Omniverse/IsaacGymEnvs#203]
I export my urdf from solidworks. I find this file is normal in **gazebo** and **mujuco**, but it seems can't work in **isaacgym**.The screenshorts are shown as below.
![10C78A321576E3F995CB8EB020750170](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/assets/92290261/27af996e-b637-44dc-b455-999eb1d5011d)
![CF179812C825D16437D7B6FC2A2DEC67](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/assets/92290261/6e0bed4d-47a8-4f5e-9366-08e937aa061d)
![86317D6C21AC66CC892E6D10A66309FC](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/assets/92290261/1ca6d378-9729-402d-8ff3-2124f7bc192a)

**Comment by shitoujie** [comment]
my robot follows the rules that 'x' is front 'y' is left and 'z' is up .Is the isaacgym's coordinate system different from other's? And how can i fix it?

**Comment by shitoujie** [comment]
`flip_visual_attachments = True` can solve this

**Comment by Jackyyaojk** [comment]
but my shadow hand doesn‘t work
