### ISSUE TITLE
PyPI Release

### ISSUE THREAD

**Issue by vwxyzjn** [NVIDIA-Omniverse/IsaacGymEnvs#23]
Hello, this is a really cool project! Would you be up to making a PyPI release so that people can install via `pip install issacgym`? It pins the version which will also help people reproduce results in the future :D

**Comment by gavrielstate** [comment]
I'm afraid that we don't plan to do a PyPI release of any of the Isaac Gym Preview releases. It doesn't fit our current licensing requirements.

**Comment by vwxyzjn** [comment]
I see ^ ^, maybe a workaround is to create a git tag release? Any bit of this information could help with reproducibility.
