### ISSUE TITLE
gelsight mesh missing in tacsl branch

### ISSUE THREAD

**Issue by edwardjjj** [NVIDIA-Omniverse/IsaacGymEnvs#239]
Hi, I find that the gelsight mesh files such as `gelsight_r15_meshes/gelsight_r15_finger_no_gel_coarse_x16_rot_z.obj` are missing in the assets folder. It would be great if you can upload them.

**Comment by edwardjjj** [comment]
Sorry, I found them. There is a link in the install instructions.

**Comment by yijionglin** [comment]
Hi @edwardjjj , could you please share the link here as well? Couldn't find it in the repo... Thanks!

**Comment by aldeW64** [comment]
Hi @edwardjjj, could you please share the link here? The original one in the repo is now locked. Thanks a lot!
