### ISSUE TITLE
Multiple anymal robots appearing in the same coordiante - AnimalTerrain

### ISSUE THREAD

**Issue by eladpar-rnd** [NVIDIA-Omniverse/IsaacGymEnvs#24]
Hey I was trying out the example Animal Terrain .
I assume each Anymal was suppose to appear in a different location?
but this is what happend:

![Screenshot from 2022-03-27 11-27-09](https://user-images.githubusercontent.com/72129770/160273501-0a077b71-39e1-4aef-ab3c-f51544af3cc5.png)

In another Question - Is  multiple gpu supported in ths issac Gym?

**Comment by gavrielstate** [comment]
That's correct behavior. They each get random velocity and yaw targets, so they spread out over time. Let them train (press 'v' to disable visualization, which makes them train faster), then reload with the trained checkpoint and fewer environments and you'll see them go everywhere.

We have a patch for better multiGPU / Horovod support coming to the IGE repo soon.
