### ISSUE TITLE
how can i modify the number of envs in the Anymal demo?

### ISSUE THREAD

**Issue by fireworksl** [NVIDIA-Omniverse/IsaacGymEnvs#26]
Anymal demo goes well when i don'tmodify the num of envs in the Anymal.yaml file, but when i modify it the simulition can't run and there is a AssertionError in a2c_common.py:  assert(self.batch_size%self.minibatch_size == 0) 

thanks!!!

**Comment by yanglh14** [comment]
You can change minibatch_size in the task config file - AnymalPPO.yaml in your example. Default is 32768. You can decrease the minibatch size to like 16384, 8192, 4096.

**Comment by fireworksl** [comment]
thank you very much ,i have resolved this problem


| |
秦道岭
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/27/2022 19:38，Yang ***@***.***> wrote：

You can change minibatch_size in the task config file - AnymalPPO.yaml in your example. Default is 32768. You can decrease the minibatch size to like 16384, 8192, 4096.
