### ISSUE TITLE
Will DeepMimic/AMP in Isaac Gym be open sourced?

### ISSUE THREAD

**Issue by floodsung** [NVIDIA-Omniverse/IsaacGymEnvs#3]

**Comment by gavrielstate** [comment]
Yes - we are working on cleaning it up for a public release, and hope to make it available later this fall.

**Comment by Frank-Dz** [comment]
> Yes - we are working on cleaning it up for a public release, and hope to make it available later this fall.

Will you release the deepmimic part?
