### ISSUE TITLE
Readiness and hard constraints

### ISSUE THREAD

**Issue by 1seck** [NVIDIA-Omniverse/IsaacGymEnvs#38]
Hi there,

when will gym be ready for primetime?
I am still with Isaac Gym on Sim and wondering when I should switch to Omniverse?

Second question:
How hard can constraints be made?
I don't know if I am doing something wrong here but no matter whether I am using Attractors or concerning the maximum force (effort) of a joint, there seem to be a reaction time until the constraint solving force is applied, meaning the constraints seem too "soft". What am I doing wrong :)

E.g. I want to have 2 actors be attached to each other but the spring (stiffness) between them seems too soft even if I set the attractor's stiffness up to 1e10 or more, same goes for the servos DOF stiffness and effort, please see the video.
On the video you can see the problem I am facing: Since I cannot fixate the different parts of the finger, I try to make the hand more stiff but without success so far.

[Video](https://youtu.be/T1OvoGcFapk)

Kind regards

**Comment by rolandying** [comment]
Hi, I'm also facing the attachment problem between two actors. How did you solve it?
