### ISSUE TITLE
[bug] stepping twice in pre_physics_step in anymal_terrain.py

### ISSUE THREAD

**Issue by boxiXia** [NVIDIA-Omniverse/IsaacGymEnvs#60]
Stepping is done twice in  anymal_terrain.py pre_physics_step() and vec_task.py step():

https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/6da538b44618afb9086be30371e5466ea182c2bf/isaacgymenvs/tasks/anymal_terrain.py#L446

https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/6da538b44618afb9086be30371e5466ea182c2bf/isaacgymenvs/tasks/base/vec_task.py#L334

Should only one stepping be done?

**Comment by gavrielstate** [comment]
AnymalTerrain has an additional control decimation parameter: https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/main/isaacgymenvs/cfg/task/AnymalTerrain.yaml#L48

It may have originally been written this way prior to the introduction of the `controlFrequencyInv` parameter though, and it may be that it could be refactored to use that instead.
