### ISSUE TITLE
Can the Envs run on A100?

### ISSUE THREAD

**Issue by RogerLZX** [NVIDIA-Omniverse/IsaacGymEnvs#66]
I have a ```NVIDIA A100 40GB PCIe GPU Accelerator``` and want to run the Envs on it. 

Is this possible?

The requirement sheet says that the Minimum Spec for GPU is ```GeForce RTX 2070```. Since ```GeForce RTX 2070``` is not only for computation, I'm not sure whether the a100 can fulfill this requirement.

**Comment by gavrielstate** [comment]
Yes, A100 works very well with Isaac Gym.
