### ISSUE TITLE
I can not disply on IsaacGym

### ISSUE THREAD

**Issue by pannatorn6395** [NVIDIA-Omniverse/IsaacGymEnvs#67]
![image](https://user-images.githubusercontent.com/81004343/180645550-a6a9f157-3f10-40af-8bac-116e09825d52.png)

**Comment by gavrielstate** [comment]
Make sure that you have a working Vulkan setup with the NVIDIA GPU set as display device 0.

Here's the troubleshooting paragraph from the install docs: 

On systems with integrated Intel graphics, make sure that the NVIDIA GPU is selected.  For example, on Ubuntu 18.04, you can run ``sudo prime-select nvidia``. If you have multiple Vulkan devices visible when running ``vulkaninfo``, you may need to explicitly force use of your NVIDIA GPU. You can do this as follows: ``export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json``
