### ISSUE TITLE
Command '['which', 'c++']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by pannatorn6395** [NVIDIA-Omniverse/IsaacGymEnvs#68]
When i try to train got some error
![image](https://user-images.githubusercontent.com/81004343/180692418-fa2377e2-6f03-4a6c-bb12-0addd19d5e20.png)

**Comment by gavrielstate** [comment]
Yes, you need a C++ compiler installed because PyTorch JIT requires it.

You can use `sudo apt install build-essential` To get what you need.
