### ISSUE TITLE
Trained controllers

### ISSUE THREAD

**Issue by zheyu98** [NVIDIA-Omniverse/IsaacGymEnvs#74]
Hi,

I'm trying to play with the shadow hand re-orientation task. But after training for several hours, the robot hand could not perform the task so well. I'm wondering if it's because I have to reduce the number of envs and the size of the mini-batch so that the code could run on my laptop. 

Have you guys shared the trained models somewhere that I could directly use to perform the tasks and compared with the one trained by myself? I could not find them in this repo.

Thanks
Zheyu

**Comment by gavrielstate** [comment]
Sorry for the late reply - we haven't previously shared pre-trained environments, but here are a couple for the OpenAI ShadowHand tasks: https://drive.google.com/drive/folders/1WJoPZik-TNe2kPFDwiajGnHLEzZFz8wN?usp=sharing - I don't think that these are fully converged. They were just some test runs before the last release.

Training is best with 8192 or 16k environments, but doesn't take too long on a high end GPU if you run in headless mode. If you run with rendering on, it's very slow.
