### ISSUE TITLE
Customizing the 4-legged robot

### ISSUE THREAD

**Issue by tunglm2203** [NVIDIA-Omniverse/IsaacGymEnvs#80]
Hi,

I was able to train the ANYmal robot from [this repo](https://github.com/leggedrobotics/legged_gym). I'm wondering is possible to customize the provided ANYmal robot to another type of 4-legged robot? If it is, is there an instruction to do this?

Thank you.

**Comment by ZiwenZhuang** [comment]
You could check the example of how [Legged_gym](https://github.com/leggedrobotics/legged_gym) is loading customized robot models. :)
