### ISSUE TITLE
Pointers to create a MA environment

### ISSUE THREAD

**Issue by bycn** [NVIDIA-Omniverse/IsaacGymEnvs#9]
Hi all, 
I'm trying to recreate the RoboSumo environment https://github.com/openai/robosumo . Could someone give me an overview / code pointers to create this? It would essentially be two Ants whose actions affect each other, along with a simple mat texture on the bottom to indicate the "ring".

**Comment by ViktorM** [comment]
Hi @bycn,

Currently, we don't have an example of multi-agent and self-play environments in Isaac Gym. But I've already had the re-implementation of robosumo working in Isaac Gym and training with rl_games internally. It could be trained in less than 2 hours on a single GPU (PC). We plan to release it in one of the next updates to IsaacGymEnvs.

**Comment by bycn** [comment]
@ViktorM Great, thanks, looking forward to the release :)
