### ISSUE TITLE
Question about the robot control in the Isaac Gym

### ISSUE THREAD

**Issue by rolandying** [NVIDIA-Omniverse/IsaacGymEnvs#90]
Hi, 
I'm new in Isaac gym, when I'm reading the `franka_cube_stack.py` example, I have one question about the robot control part.
In the code of `franka_cube_stack.py`, looks like they directly implement the `Actions` on the  `end-effector joint`
So when controlling the robot, could we just directly implement the position or force control of the end-effector in the Cartesian coordinate system without considering the forward or inverse dynamic? Would the Isaac gym take care of the dynamics?

Specifically, when implementing the actions in function `pre_physics_step()` in `franka_cube_stack.py`:
https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/ca7a4fb762f9581e39cc2aab644f18a83d6ab0ba/isaacgymenvs/tasks/franka_cube_stack.py#L655-L656
why the target position is `self._pos_control` and `self._effort_control`？ Can't find the update of the `self._pos_control` or `self._effort_control` for each step.

**Comment by XuSeeYoung** [comment]
Hi， I also find this problem. Have you made it clear?
Is the code wrong?
