### ISSUE TITLE
There is trojan inside your files

### ISSUE THREAD

**Issue by pedped** [NVIDIA-Omniverse/IsaacGymEnvs#93]
Hi

Today I tried to download the codes, but it has trojan and my windows blocked the download, I have attached an screenshot for your reference 

![image](https://user-images.githubusercontent.com/5029899/202853256-439c920c-da0b-4538-8f28-d936b92060dc.png)

**Comment by gavrielstate** [comment]
We do not host any files on GitHub, only code downloadable via git. Your download must have come from somewhere else.
