### ISSUE TITLE
Documentation website down?

### ISSUE THREAD

**Issue by BolunDai0216** [NVIDIA-Omniverse/IsaacGymEnvs#97]
Hi,

Is the documentation located here: https://www.gymlibrary.ml/content/vector_api/?

If so, is the website down? I can't open it.

**Comment by gavrielstate** [comment]
IsaacGymEnvs documentation is available here: https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/tree/main/docs

The bad link above was for the OpenAI Gym library vectorized environment documentation. That link has been updated in our README
