### ISSUE TITLE
Are there plans to incorporate uploading custom terrains?

### ISSUE THREAD

**Issue by tnilest** [NVIDIA-Omniverse/IsaacGymEnvs#99]
I know that there is the ability to provide generation parameters for rough terrain, or slopes, but is there any planed support for uploading entire pre-generated terrains in USD or other similar formats?

**Comment by gavrielstate** [comment]
On the Omniverse side of things you should be able to just go ahead and add your own terrain as a USD object. You can check out the code here for how the generated terrain gets added in that version: https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/blob/main/omniisaacgymenvs/utils/terrain_utils/terrain_utils.py#L367

We will not be updating the standalone Isaac Gym version to support anything beyond the current terrain APIs.
